# exp setting
<<<<<<< Updated upstream
exp_name: 'test' # name that will be used in wandb
ckpt_path: null # checkpoint path, used for evaluation
=======
exp_name: 'mtr_real' # name that will be used in wandb
ckpt_path: '/home/wz2708/unitraj/unitraj/unitraj_ckpt/mtr_real/epoch=70-val/brier_fde=0.61.ckpt'
>>>>>>> Stashed changes
seed: 42 # random seed
debug: True # debug mode, will use cpu only
devices: [ 0 ] # gpu ids

# data related
<<<<<<< Updated upstream
load_num_workers: 0 # number of workers for loading data
train_data_path: [ "data_samples/nuscenes" ] # list of paths to the training data
val_data_path: [ "data_samples/nuscenes" ] # list of paths to the validation data
=======
# 0 filter 1 augment 2 real 3 ground truth
load_num_workers: 16 # number of workers for loading data
train_data_path: [ "data_samples/cosmos/metadrive2/cosmos_l20_f2p5/train" ] # list of paths to the training data
# val_data_path: [ "data_samples/cosmos/metadrive2/cosmos_l20_f2p5/val" ] # list of paths to the validation data
val_data_path: [ "data_samples/cosmos/metadrive3/cosmos_l20_f2p5/test" ]

>>>>>>> Stashed changes
cache_path: "./cache"
max_data_num: [ null ] # maximum number of data for each training dataset, null means all data
starting_frame: [ 0 ] # history trajectory starts at this frame for each training dataset
past_len: 21 # history trajectory length, 2.1s
future_len: 60 # future trajectory length, 6s
object_type: [ 'VEHICLE' ]#, 'PEDESTRIAN', 'CYCLIST'] # object types included in the training set
line_type: [ 'lane','stop_sign','road_edge','road_line','crosswalk','speed_bump' ] # line type to be considered in the input
masked_attributes: [ 'z_axis', 'size' ] # attributes to be masked in the input
trajectory_sample_interval: 1 # sample interval for the trajectory
only_train_on_ego: False # only train on AV
center_offset_of_map: [ 30.0, 0.0 ] # center offset of the map
use_cache: False # use cache for data loading
overwrite_cache: False # overwrite existing cache
store_data_in_memory: False # store data in memory

# official evaluation
nuscenes_dataroot: '/mnt/nas3_rcp_enac_u0900_vita_scratch/datasets/Prediction-Dataset/nuscenes/nuscenes_root'
eval_nuscenes: False # whether to evaluate with nuscenes evaluation tool
eval_waymo: False # whether to evaluate with waymo evaluation tool
eval_argoverse2: False # whether to evaluate with argoverse evaluation tool

defaults:
  - method: MTR